kind: ConfigMap
apiVersion: v1
metadata:
  name: account
  namespace: bookstore-microservices
data:
  config.toml: |-
    [db]
    host = "host.docker.internal"
    port = 3306
    user = "root"
    password = "12345678"
    database = "bookstore"