apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-microservices-domain-account
  namespace: bookstore-microservices
  labels:
    app: account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      serviceAccountName: book-admin
      containers:
        - name: account
          image: icyfenix/bookstore-domain-account
          ports:
            - containerPort: 8810
