kind: Service
apiVersion: v1
metadata:
  name: gateway
  namespace: bookstore-microservices
  labels:
    app: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - port: 8888
      targetPort: http-server
      # 30000-32767
      nodePort: 30080