kind: Deployment
apiVersion: apps/v1
metadata:
  name: bookstore-domain-payment
  namespace: bookstore-microservices
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      serviceAccountName: book-admin
      containers:
        - name: payment
          image: icyfenix/bookstore-domain-payment
          ports:
            - name: server
              containerPort: 8812