kind: Deployment
apiVersion: apps/v1
metadata:
  name: bookstore-domain-warehouse
  namespace: bookstore-microservices
  labels:
    app: warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse
  template:
    metadata:
      labels:
        app: warehouse
    spec:
      serviceAccountName: book-admin
      containers:
        - name: warehouse
          image: icyfenix/bookstore-domain-warehouse
          ports:
            - containerPort: 8888
              name: rpc-server
          env:
            - name: CONFIG_PATH
              value: /app/conf/config.toml
          volumeMounts:
            - name: config-volume
              mountPath: /app/conf
      # 映射configmap
      volumes:
        - name: config-volume
          configMap:
            name: warehouse
